-- =====================================================
-- SLC CUTS - MASTER SCHEMA
-- Complete database structure for Barberia & Shop
-- =====================================================

-- Reset Tables (Optional: Use with caution)
DROP TABLE IF EXISTS public.page_visits CASCADE;
DROP TABLE IF EXISTS public.news CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.stock CASCADE;
DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.gallery_images CASCADE;

-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  role TEXT DEFAULT 'client' CHECK (role IN ('admin', 'client')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger for new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, role)
  VALUES (new.id, new.email, 'client');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. CATEGORIES
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. PRODUCTS
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  is_offer BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. PRODUCT IMAGES
CREATE TABLE public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. STOCK
CREATE TABLE public.stock (
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE PRIMARY KEY,
  quantity INTEGER DEFAULT 0 CHECK (quantity >= 0),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Stock Triggers
CREATE OR REPLACE FUNCTION public.handle_new_product_stock() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.stock (product_id, quantity)
  VALUES (new.id, 0);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_product_created
  AFTER INSERT ON public.products
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_product_stock();

-- 6. ORDERS
CREATE TABLE public.orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  customer_email TEXT,
  total_price DECIMAL(10, 2) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled', 'shipped')),
  shipping_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Function to deduct stock on payment
CREATE OR REPLACE FUNCTION public.handle_stock_deduction() 
RETURNS TRIGGER AS $$
BEGIN
  IF (NEW.status = 'paid' AND (OLD.status IS NULL OR OLD.status != 'paid')) THEN
    UPDATE public.stock s
    SET quantity = s.quantity - oi.quantity,
        updated_at = NOW()
    FROM public.order_items oi
    WHERE oi.order_id = NEW.id
      AND oi.product_id = s.product_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_order_paid
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW EXECUTE PROCEDURE public.handle_stock_deduction();

-- 7. ORDER ITEMS
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

-- 8. SETTINGS
CREATE TABLE public.settings (
  key TEXT PRIMARY KEY,
  value BOOLEAN DEFAULT FALSE
);

INSERT INTO public.settings (key, value) VALUES ('flash_offers_enabled', false) ON CONFLICT DO NOTHING;

-- 9. GALLERY
CREATE TABLE public.gallery_images (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  image_url TEXT NOT NULL,
  description TEXT,
  alt_text TEXT DEFAULT 'Imagen de galería',
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. NEWS
CREATE TABLE public.news (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL,
    image_url TEXT,
    is_published BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. ANALYTICS
CREATE TABLE public.page_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT NOT NULL,
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_visits ENABLE ROW LEVEL SECURITY;

-- ADMIN CHECK FUNCTION (Helper)
CREATE OR REPLACE FUNCTION is_admin() 
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role = 'admin'
    )
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Public Access (Read Only)
CREATE POLICY "Public read products" ON public.products FOR SELECT USING (active = true);
CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public read images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Public read stock" ON public.stock FOR SELECT USING (true);
CREATE POLICY "Public read settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Public read gallery" ON public.gallery_images FOR SELECT USING (active = true);
CREATE POLICY "Public read news" ON public.news FOR SELECT USING (is_published = true);

-- Analytics Access
CREATE POLICY "Allow insert visits" ON public.page_visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow read visits" ON public.page_visits FOR SELECT USING (is_admin());

-- Client Access (Their own orders)
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id OR customer_email = (SELECT email FROM auth.users WHERE id = auth.uid()));

-- Admin Access (Full)
CREATE POLICY "Admin full access users" ON public.users FOR ALL USING (is_admin());
CREATE POLICY "Admin full access categories" ON public.categories FOR ALL USING (is_admin());
CREATE POLICY "Admin full access products" ON public.products FOR ALL USING (is_admin());
CREATE POLICY "Admin full access images" ON public.product_images FOR ALL USING (is_admin());
CREATE POLICY "Admin full access stock" ON public.stock FOR ALL USING (is_admin());
CREATE POLICY "Admin full access orders" ON public.orders FOR ALL USING (is_admin());
CREATE POLICY "Admin full access order_items" ON public.order_items FOR ALL USING (is_admin());
CREATE POLICY "Admin full access settings" ON public.settings FOR ALL USING (is_admin());
CREATE POLICY "Admin full access gallery" ON public.gallery_images FOR ALL USING (is_admin());
CREATE POLICY "Admin full access news" ON public.news FOR ALL USING (is_admin());
